#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
$OPENSHIFT_DATA_DIR/bin/pip install --use-mirrors -r $OPENSHIFT_REPO_DIR/requirements.txt
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/$OPENSHIFT_APP_NAME/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/$OPENSHIFT_APP_NAME/manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/$OPENSHIFT_APP_NAME/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/$OPENSHIFT_APP_NAME/manage.py collectstatic --noinput

